name: Llama Index Integration Tests

on: [pull_request]

defaults:
  run:
    shell: bash
    working-directory: ./python

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "test_llama_index.py"